version: "3"
services:
  my-web-app-db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Film2NightMySQL2
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  my-web-app:
    build: .
    ports:
      - "8181:8080"
    depends_on:
      - my-web-app-db
    volumes:
      - ./Posters:/app/Posters
    user: root

volumes:
  db-data:
